# Generated by Django 4.1.4 on 2022-12-18 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=100)),
                ('middlename', models.CharField(blank=True, max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=300)),
                ('address', models.CharField(max_length=300)),
                ('city', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('color1', models.CharField(max_length=100)),
                ('color2', models.CharField(max_length=100)),
                ('color3', models.CharField(max_length=100)),
            ],
        ),
    ]
