# Generated by Django 4.1.4 on 2022-12-18 06:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_prank'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Prank',
        ),
    ]
