# Generated by Django 4.1.4 on 2022-12-20 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_delete_element'),
    ]

    operations = [
        migrations.CreateModel(
            name='Element',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=200)),
                ('visit', models.CharField(max_length=200)),
                ('perc', models.CharField(max_length=200)),
            ],
        ),
    ]
