# Generated by Django 4.1.4 on 2022-12-20 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_element'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Element',
        ),
    ]
