# Generated by Django 4.1.4 on 2022-12-20 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_element'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='element',
            name='perc',
        ),
    ]
